# QUAN TRỌNG: Trong production dùng Vault hoặc AWS Secrets Manager
# Không commit file này vào git (thêm vào .gitignore)
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: airline
type: Opaque
stringData:
  BOOKING_DB_URL:   "postgresql://postgres:postgres@postgres-postgresql.airline:5432/booking_db"
  INVENTORY_DB_URL: "postgresql://postgres:postgres@postgres-postgresql.airline:5432/inventory_db"
  PRICING_DB_URL:   "postgresql://postgres:postgres@postgres-postgresql.airline:5432/pricing_db"
  JWT_SECRET:       "change-me-before-production-min-32-chars"
