apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: airline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: airline/inventory-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: INVENTORY_DB_URL
        envFrom:
        - configMapRef:
            name: shared-config
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: airline
spec:
  selector:
    app: inventory-service
  ports:
  - port: 3002
    targetPort: 3002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-hpa
  namespace: airline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-service
  minReplicas: 2
  maxReplicas: 20      # inventory cần scale nhiều hơn vì lock requests cao
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
